import "./globals.css";
import Header from "../components/Header";
import NextAuthProvider from "./auth/NextAuthProvider";

const mainColor = "#0b1021";
const textColor = "#fff";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({ children }) {
  return (
    <html dir="rtl" lang="fa">
      <body
        style={{ backgroundColor: `${mainColor}`, color: `${textColor}` }}
        className="max-w-[1600px] relative mx-auto"
      >
        <NextAuthProvider>
          <Header />
          {children}
        </NextAuthProvider>
      </body>
    </html>
  );
}
